Newbranch
igorkol91/NYTarticle pull request #1
Opened 2021-03-23 23:17 UTC by igorkol91

2021-03-24 14:12 UTC, christianotieno requested changes
## Changes Required ♻️ 
Hello @igorkol91 👋🏾 

Thank you for submitting your `Positioning and Floating Elements` project for the first review. The codebase is clean, DRY for the majority of parts of the codebase saved for a few, and free of commented out code. It is quite commendable how you have strived to keep the repository professional for majority of parts.  Keep it up 👏🏾 

Before this gets approved, we need to make sure nothing is messed up. Kindly take care of some highlighted issues down below. 👇🏾 

**Kindly note: that this will act as a first review and after which the pull request will have only two more review chances for it to get approved. I would urge we try and work on the suggested changes with utmost keenness** 

### Mandatory changes
- [ ] Improve the `navbar`  to match the source page.
- [ ] Improve the main article's image section to match the source page.
- [ ] Improve the `Theory of Inflation' section to match the source page.
- [ ] Improve the footer of the page.
- [ ] Implement the highlighted missing sections.
- [ ] Improve the project's highlighted sections.
### Happy coding 💻 
#### Christian Otieno (CR)

2021-03-24 14:12 UTC, christianotieno commented on README.md
> +New York Times Article Clone
## Improve the README
- [ ] Inline with having a descriptive README, do you mind adding an alive link to where the page is hosted live? 

You can use this [template ](https://github.com/microverseinc/readme-template)from [pathwright ](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)for inspiration. You are also welcomed to use this [tool ](https://raw.githack.com/)to generate a live link.

2021-03-24 14:12 UTC, christianotieno commented on index.html
> +<!DOCTYPE html>
### Validate the markup
- [ ] We need to ensure that our markup does not have any informing warnings. Do you mind validating our markup?
You are free to use this [tool ](https://validator.w3.org/nu/#textarea)for easier validation.

2021-03-24 14:12 UTC, christianotieno commented on index.html
> +            <img src="./ny-times-logo.png" alt="main-header-logo">
### Navigation bar
- [ ] Kindly ensure The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)). Currently, we have an image which is a good thing. Do you mind turning it into a link?

2021-03-24 14:12 UTC, christianotieno commented on index.html
> +
### ADD missing sections in the main article.
- [ ] There are some missing social links at the top of the main article's image. Do you mind adding them?

|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://raw.githack.com/igorkol91/NYTarticle/newbranch/index.html)|
|:--:|:--:|
|![Main-Article-socials-source](https://user-images.githubusercontent.com/22345961/112321452-11ca9d00-8cc1-11eb-909a-1ba1beff5725.png)|![Main-Article-socials](https://user-images.githubusercontent.com/22345961/112321467-1727e780-8cc1-11eb-929d-55b76f99bd54.png)|

2021-03-24 14:12 UTC, christianotieno commented on index.html
> +                        <img src="./inflation-945.png" alt="inflation-big-img">
### Required: Full implementation of the `Theory of Inflation`
- [ ] This section you appeared to have to the screenshot and included it in the clone page. Kindly ensure that this section is fully implemented and all the items styled accordingly. You stand a chance to gain more experience from its implementation. Avoid using screenshots of the original page as a shortcut to bypass requirements for this and future projects. Thank you.

2021-03-24 14:12 UTC, christianotieno commented on index.html
> +                    <iframe width="420" height="315" title="youtube-vid" src="https://youtu.be/ZlfIVEy_YOA">
### FIX the video not showing
- [ ] The video currently is not showing as expected. Do you mind fixing this?

Below is a comparison of what is expected and what we currently have.

|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://raw.githack.com/igorkol91/NYTarticle/newbranch/index.html)|
|:--:|:--:|
|![video](https://user-images.githubusercontent.com/22345961/112320988-9668eb80-8cc0-11eb-95bc-c2136e50c5e4.png)|![video-clone](https://user-images.githubusercontent.com/22345961/112321027-9f59bd00-8cc0-11eb-9d4b-32c9602d14b3.png)|

2021-03-24 14:12 UTC, christianotieno commented on index.html
> +
### Implement missing sections 
The following sections have not been implemented on the clone page. I have highlighted them below for easier reference. 

#### Suggested newsletters section

**NOTE: Do you mind also include in the implementation, the `READ 615 Comments` and the preceding social links as well?**

![Suggested-newsletters-section](https://user-images.githubusercontent.com/22345961/112322162-b77e0c00-8cc1-11eb-9d75-5167dba00c0f.png)

#### More into space and astronomy

![more-inspace-and-astronomy](https://user-images.githubusercontent.com/22345961/112322206-c4026480-8cc1-11eb-8411-08b31cad9b74.png)

#### Editors pick

![editors-pick-footer](https://user-images.githubusercontent.com/22345961/112322262-ce246300-8cc1-11eb-800f-4f53fb028cd6.png)

2021-03-24 14:12 UTC, christianotieno commented on index.html
> +                    <li><a href="#" class="footer-link">Television</a></li>
### Imrove the `Footer` Section

- [ ] A closer look at the footer, we can see the contrast. On the Source page, we have the page's logo and contents are divided into visible borders. Do you mind improving these areas?

|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://raw.githack.com/igorkol91/NYTarticle/newbranch/index.html)|
|:--:|:--:|
|![footer](https://user-images.githubusercontent.com/22345961/112322703-2fe4cd00-8cc2-11eb-89cd-6e9753263bdf.png)|![footer-clone](https://user-images.githubusercontent.com/22345961/112322722-3410ea80-8cc2-11eb-941a-d59cdb637f4c.png)|

2021-03-24 14:12 UTC, christianotieno commented on index.html
> +    </section>
### Optional Change
- [ ] Do you mind while conducting the above changes, implement the sticky section bottom of the footer that sticks to the bottom of the page as well?

2021-03-24 14:12 UTC, christianotieno commented on main.css
> +}
## Aim to remain DRY
- [ ] We appear to be repeating ourselves in lines `#193` & `#198`. Do you mind merging these rules?

2021-03-24 16:44 UTC, christianotieno commented on README.md
> +New York Times Article Clone
### Improve the Commit and Pull Request Message
- [ ] Your commit messages don't appear to be well informed of what the changes getting added are dong. Do you mind being more elaborate with the commit messages?
- [ ] Kindly note that the Pull Request message ought to communicate what the changes in the said branch are introducing in the main codebase (Changes to be merged). So your mind improving the Pull Request message to showcase to the reviewer what changes/work was carried out in this branch? 

Check this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) for inspiration on how to go about it.

2021-03-25 11:18 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @igorkol91 :wave:

__You've really done well so far. Thank you for fixing most of the required changes by the last reviewer:__

__However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] The live demo link is still missing in your Readme. Are you having any challenge(s) doing this? You can use either Github pages or the [githack cdn](https://raw.githack.com/)
- [ ] As mentioned by the last reviewer, you're having some formatting issues in your Readme. Kindly use [this template](https://github.com/microverseinc/readme-template) as a guide.
- [ ] Looks like the newly implemented sections are not properly structured. Kindly check the `Suggested news for you`, `More in Space and Astronomy`, `Most Popular`, and the bottom navigation items. Please compare your implementation with that of the original page and make all necessary corrections.
- [ ] You're having the `.vscode` directory in your remote folder structure. Do not commit any file/folder that is not related to the project. Let's fix this. 
The easiest way to do this is to:
- Delete the `.vscode` locally from your project root directory
- Add the `.vscode` directory to your `.gitignore` file. The [.gitignore](https://www.freecodecamp.org/news/gitignore-what-is-it-and-how-to-add-to-repo/) is a file, not a folder (I can see you added it as a folder). Do not skip the initial `.`, which is part of the directory name (i.e. `/.vscode`).
- Add and commit your changes.
- You can then restore the `.vscode` directory from the Cycle bin to your project if you still need it for developmental purposes.

**[ OPTIONAL CHANGES ]**

- [ ] You've used a lot of `id` selectors for your CSS rules. Personally, I feel like this behavior is not the conventional way of doing things. You should use the `class` selectors extensively in your project. This is because the `id` attribute has higher precedence than its `class` counterpart. If care is not taken, it might end up messing with the cascading nature of your CSS rules. You may want to refactor your code.

* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

**REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 1 code review left for this project. If you think that the code review was not fair, you can [request a second-opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).**

_**Please make the required changes and submit another review request when you are done.**_

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-03-25 19:00 UTC, christianotieno reviewed
## Project Approved 🍾 
Hello @igorkol91 👋🏾 
Congratulations. The project is now approved. 👏🏾 
All the very best in your next tasks 🥇 

Happy coding 💻 
Christian Otieno (CR)

2021-03-26 12:01 UTC, merged